---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fury-distribution
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./fury
  prune: true
  sourceRef:
    kind: GitRepository
    name: fury-distribution

